---

- name: Copy FROM to SAME Remote Server
  hosts: pcldevweb06

  vars_files:
    - vars/directory_info.yaml

  tasks:
  - name: Copy FROM and TO Same Remote Server
    win_copy:
      src: '{{ SRC_DIR }}/'
      dest: '{{ DEST_DIR }}'
      backup: no
      remote_src: yes

...

